# Generated by Django 2.1.15 on 2023-03-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20230307_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpostmodel',
            options={'ordering': ('-post_title',), 'verbose_name_plural': 'Posts'},
        ),
    ]
