# Generated by Django 4.2 on 2023-04-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('User', 'User')], default=False, max_length=50),
        ),
    ]
