# Generated by Django 2.1.15 on 2023-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20230307_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpostmodel',
            options={'ordering': ('-post_title',), 'verbose_name_plural': 'Client Post'},
        ),
        migrations.AddField(
            model_name='addpostmodel',
            name='bidamount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addpostmodel',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
