version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip ./sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:./sonar-scanner-4.7.0.2747-linux/bin/
  build:
    commands:
      - pylint --disable=C0410,W0611 *.py **/*.py || true
      - sonar-scanner -Dsonar.login=584d244ffb7cfe556e0a7a5cc3a2ce06bf4ef631 -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=akshu3626 -Dsonar.organization=akshu3626 -DgeneratePom=true
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=akshu3626 >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi