version: 0.1
os: linux
files:
  - source: freelancer
    destination: /home/ec2-user/django-aws_cicd
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
  AfterInstall:
      - location: scripts/after_install.sh
