# Generated by Django 2.1.15 on 2023-03-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('freelancer', 'freelancer')], default=False, max_length=2),
        ),
    ]
